
LAN_OPERATOR.addIndexes({
			mark:'Traceper Takip Sistemi',		
			aboutTitle:'Hakk\u0131m\u0131zda',
			usersTitle:'Kullan\u0131c\u0131lar',
			searchResultsTitle:'Arama Sonu\u00E7lar\u0131',
			returnToUserListLink:'&laquo; Kullan\u0131c\u0131 listesine d\u00F6n',
			returnToPhotoListLink:'&laquo; Resimler listesine d\u00F6n',
//			loading:'Y\u00FCkleniyor',
			noMatchFound:'Uygun sonu\u00E7 bulunamad\u0131',
			realname:'Ad',
			time:'Zaman',
			deviceId:'Cihaz no',
			latitude:'Enlem',
			longitude:'Boylam',
			searchStringIsTooShort:'L\u00FCtfen aranmas\u0131 i\u00E7in daha uzun kelime giriniz.',
			aboutus:'<div class=\"logo\"></div>traceper cep telefonlarÄ±nÄ± kullanan bir GPS takip sistemidir, traceper Ã¼cretsiz, aÃ§Ä±k kaynak kodlu ve kullanÄ±mÄ± basit bir yazÄ±lÄ±m olup Ã§alÄ±ÅŸmasÄ± iÃ§in herhangi bir GPS takip aracÄ±na ihtiyaÃ§Ä± yoktur, sadece gps destekleyen cep telefonlarÄ±na ihtiyaÃ§ duyar ve biz de yakÄ±n gelecekte tÃ¼m cep telefonlarÄ±nÄ±nÄ±n GPS destekli olacaÄŸÄ±nÄ± dÃ¼ÅŸÃ¼nÃ¼yoruz.<br/><br/><div class=\"title\">Destek</div>Bu yazÄ±lÄ±mÄ± kullanmak veya deÄŸiÅŸtirmek isterseniz sahip olduÄŸumuz tÃ¼m bilgiyi paylaÅŸmaya hazÄ±rÄ±z, bu yÃ¼zden lÃ¼tfen iletiÅŸime geÃ§mek iÃ§in tereddÃ¼t yaÅŸamayÄ±nÄ±z.<br/><br/><div class=\"title\">Lisans</div>Bu yazÄ±lÄ±m Ã¼cretsizdir, haber vermeden deÄŸiÅŸtirilebilir veya daÄŸÄ±tÄ±labilir.<br/><br/><div class=\"title\">Tekzip</div>Bu yazÄ±lÄ±m hiÃ§ bir ÅŸeyi garanti etmez, yazÄ±lÄ±mÄ± kullanÄ±rken bÃ¼tÃ¼n sorumluluk kullanana aittir. Herhangi bir durumda kesinlikle sorumluluk kabul edilmez.<br/><br/><div class=\"title\">Proje Ekibi</div>Ozan KÃ¶roÄŸlu - koroglu.ozan@gmail.com <br/>Ahmet OÄŸuz Mermerkaya - ahmetmermerkaya@gmail.com',
			zoom:'YakÄ±nlaÅŸtÄ±r',
			zoomMax:'En yakÄ±n',
			drawTraceLine:'Ä°z doÄŸrularÄ±nÄ± Ã§iz',
			wasHere:'burdaydÄ±.',
			previousPoint:'<< Ã–nceki nokta',
			nextPoint:'Sonraki nokta >>',
			noMorePastDataAvailable:'Bu kullan\u0131c\u0131 i\u00E7in daha eski bulunduÄŸu noktalar veritabanÄ±nda mevcut deÄŸildir',
			clearTraceLines:'DoÄŸrularÄ± temizle',
			operations:'Ä°ÅŸlemler',
			photosTitle:'Resimler',
			photosSearchBox:'YÃ¼kleyene gÃ¶re resim ara',
			usersSearchBox:'KullanÄ±cÄ± ara',
			next:'Sonraki >',
			previous:'< Ã–nceki',
			uploader:'YÃ¼kleyen',
			usernameLabel:'Kullan\u0131c\u0131 Ad\u0131',
			passwordLabel:'Å�ifre',
			submitFormButtonLabel:'G\u00F6nder',
			cancelFormButtonLabel:'Vazge\u00E7',
			incorrectPassOrUsername:'Kullan\u0131c\u0131 Ad\u0131 veya ÅŸifre hatalÄ±!',
			hi:'Selam',
			signout:'Ã‡Ä±kÄ±ÅŸ',
			rememberMeLabel:'Beni hatÄ±rla',
			emailLabel:'E-posta',
			emailNotFound:'E-posta adresi bulunamadÄ±.',
			sendNewPassword:'Yeni ÅŸifre gÃ¶nder',
			showLoginForm:'GiriÅŸ formunu gÃ¶ster',
			forgotPassword:'Å�ifremi unuttum',
			currentPasswordLabel:'Å�imdiki ÅŸifre',
			newPasswordLabel:'Yeni ÅŸifre',
			newPasswordAgainLabel:'Yeni ÅŸifre(tekrar)',
			enterSamePassword:'LÃ¼tfen yeni ÅŸifre kutucuklarÄ±na aynÄ± ÅŸifreyi giriniz',
			newPasswordSent:'Yeni ÅŸifre e-posta adresinize gÃ¶nderilmiÅŸtir.',
			passwordChanged:'Å�ifre baÅŸarÄ±yla deÄŸiÅŸtirildi',
			currentPasswordDoesntMatch:'Girilen ÅŸifre ÅŸimdiki ÅŸifre ile aynÄ± deÄŸil',
			warningMissingParameter:'Eksik parametre, form dolduruyorsanÄ±z lÃ¼tfen tÃ¼m gerekli alanlarÄ± boÅŸ bÄ±rakmayÄ±nÄ±z',
			confirmationMessage:'Bu işlemi yapmak istediğinize emin misiniz?',
			errorInOperation:'İşlem yapılamadı!'
		});
