
LAN_OPERATOR.addIndexes({
			mark:'Traceper Takip Sistemi',		
			aboutTitle:'Hakk\u0131m\u0131zda',
			usersTitle:'Kullan\u0131c\u0131lar',
			searchResultsTitle:'Arama Sonu\u00E7lar\u0131',
			returnToUserListLink:'&laquo; Kullan\u0131c\u0131 listesine d\u00F6n',
			returnToPhotoListLink:'&laquo; Resimler listesine d\u00F6n',
//			loading:'Y\u00FCkleniyor',
			noMatchFound:'Uygun sonu\u00E7 bulunamad\u0131',
			realname:'Ad',
			time:'Zaman',
			upLoadtime:'Yükleme zamanı',
			deviceId:'Cihaz no',
			latitude:'Enlem',
			longitude:'Boylam',
			searchStringIsTooShort:'L\u00FCtfen aranmas\u0131 i\u00E7in daha uzun kelime giriniz.',
		    aboutus:'<div class=\"logo\"></div>traceper cep telefonlarını kullanan bir GPS takip sistemidir, traceper ücretsiz, açık kaynak kodlu ve kullanımı basit bir yazılım olup çalışması için herhangi bir GPS takip aracına ihtiyaçı yoktur, sadece gps destekleyen cep telefonlarına ihtiyaç duyar ve biz de yakın gelecekte tüm cep telefonlarınının GPS destekli olacağını düşünüyoruz.<br/><br/><div class=\"title\">Destek</div>Bu yazılımı kullanmak veya değiştirmek isterseniz sahip olduğumuz tüm bilgiyi paylaşmaya hazırız, bu yüzden lütfen iletişime geçmek için tereddüt yaşamayınız.<br/><br/><div class=\"title\">Lisans</div>Bu yazılım ücretsizdir, haber vermeden değiştirilebilir veya dağıtılabilir.<br/><br/><div class=\"title\">Tekzip</div>Bu yazılım hiç bir şeyi garanti etmez, yazılımı kullanırken bütün sorumluluk kullanana aittir. Herhangi bir durumda kesinlikle sorumluluk kabul edilmez.<br/><br/><div class=\"title\">İletişim</div><a href=\"mailto:contact@mekya.com\">contact@mekya.com</a><br/><br/><div class=\"title\">Proje Ekibi</div><div id=\"projectteam\">Adnan Kalay - adnankalay@gmail.com <br/> Ahmet Oğuz Mermerkaya - ahmetmermerkaya@gmail.com <br/> Eren Alp Çelik - erenalpcelik@gmail.com <br/> Murat Salman - salman.murat@gmail.com </div>',
			zoom:'Yakınlaştır',
			zoomMax:'En yakın',
			drawTraceLine:'İz doğrularını çiz',
			wasHere:'burdaydı.',
			previousPoint:'<< Önceki nokta',
			nextPoint:'Sonraki nokta >>',
			noMorePastDataAvailable:'Bu kullan\u0131c\u0131 i\u00E7in daha eski bulunduğu noktalar veritabanında mevcut değildir',
			clearTraceLines:'Doğruları temizle',
			operations:'İşlemler',
			photosTitle:'Resimler',
			photosSearchBox:'Yükleyene göre resim ara',
			usersSearchBox:'Kullanıcı ara',
			next:'Sonraki >',
			previous:'< Önceki',
			uploader:'Yükleyen',
			usernameLabel:'Kullan\u0131c\u0131 Ad\u0131',
			passwordLabel:'Şifre',
			submitFormButtonLabel:'G\u00F6nder',
			login:'Giriş',
			cancelFormButtonLabel:'Vazge\u00E7',
			incorrectPassOrUsername:'Kullan\u0131c\u0131 Ad\u0131 veya şifre hatalı!',
			unauthorizedAccess:'Yetkisiz kullanım',
			hi:'Selam',
			signout:'Çıkış',
			rememberMeLabel:'Beni hatırla',
			emailLabel:'E-posta',
			invitationMessage:'Mesaj:',
			emailNotFound:'E-posta adresi bulunamadı.',
			sendNewPassword:'Yeni şifre gönder',
			forgotPassword:'Şifremi unuttum',
			currentPasswordLabel:'Şimdiki şifre',
			newPasswordLabel:'Yeni şifre',
			newPasswordAgainLabel:'Yeni şifre(tekrar)',
			enterSamePassword:'Lütfen yeni şifre kutucuklarına aynı şifreyi giriniz',
			newPasswordSent:'Yeni şifre e-posta adresinize gönderilmiştir.',
			passwordChanged:'Şifre başarıyla değiştirildi',
			currentPasswordDoesntMatch:'Girilen şifre şimdiki şifre ile aynı değil',
			warningMissingParameter:'Eksik parametre, form dolduruyorsanız lütfen tüm gerekli alanları boş bırakmayınız',
			confirmationMessage:'Bu işlemi yapmak istediğinize emin misiniz?',
			addFriendRequestConfirmation:'%s kullan\u0131c\u0131s\u0131na arkadaşl\u0131ık isteği göndermek isteğinize emin misiniz?',
			acceptFriendRequestConfirmation:'%s kullan\u0131c\u0131s\u0131n\u0131n arkadaşl\u0131ık isteğini onayl\u0131yor musunuz?',
			deleteFriendshipConfirmation:'%s kullan\u0131c\u0131s\u0131n\u0131 arkadaş listenizden ç\u0131karmak isteğinize emin misiniz?',
			errorInOperation:'İşlem yapılamadı!',
			inviteUserLabel:'Davetiye gönder',
			dataRecordedCheckYourEmail:'Bilgileriniz başarıyla kaydedilmiştir, hesabınızı aktif hale getirmek için e-mailinizi kontrol ediniz.',
			emailAlreadyExist:'Bu e-posta adresi kayıtlarda zaten bulunmaktadır. İsterseniz, \'Şifremi unuttum\'u kullanabilirsiniz. ',
			emailNotValid:'Girdiğiniz e-posta adresi e-posta yapısında değildir!!',
			activateAccountSuccesful:'Hesabınız onaylanmıştır. Giriş yapabilirsiniz.',
			activatedAccountMailNotFound:'E-posta adresiniz aktivasyon listemizde bulunamadı.',
			activatedAccountKeysDontMatch:'Bir seyler hatalı olmalı, Baglantınızın dogru oldugundan emin olun.',
			HomePage:'Anasayfa',
			changePassword:'Şifremi değiştir',
			friendRequestRecorded:'Arkadaşlık isteği başarıyla kaydedildi.',
			friendRequests:'Arkadaşlık istekleri'
			mailEntranceRule:'Lütfen e-posta adreslerini noktalı virgül(;) ile ayırınız.',
			registerLabel:'Kayıt Ol'
		});
