
LAN_OPERATOR.addIndexes({
			mark:'Traceper Tracking System',	
			aboutTitle:'About',
			usersTitle:'Users',
			searchResultsTitle:'Search Results',
			returnToUserListLink:'&laquo; Return to user list',
			returnToPhotoListLink:'&laquo; Return to photo list',
//			loading:'Loading',
			noMatchFound:'no match found',
			realname:'Name',
			time:'Date',
			upLoadtime:'Upload time',
			deviceId:'Device id',
			latitude:'Latitude',
			longitude:'Longitude',
			searchStringIsTooShort:'Please write a longer word to search',			
			aboutus:'<div class=\"logo\"></div>traceper is a GPS tracking system via mobile phones, it is free, it is open source, it is simple and it does not require any GPS tracking device, it only uses mobile phones and we think that all mobile phones will support GPS in the near future.<br/><br/><div class=\"title\">Support</div>If you need support to modify and use this software, We can share all information we have, so feel free to contact us.<br/><br/><div class=\"title\">License</div>This software is free. It can be modified and distributed without notification.<br/><br/><div class=\"title\">Disclaimer</div>This software guarantees nothing, use it with your own risk. No responsilibity is taken for any situation.<br/><br/><div class=\"title\">Project Team</div>Ozan Koroglu - koroglu.ozan@gmail.com <br/>Ahmet Oguz Mermerkaya - ahmetmermerkaya@gmail.com',
			termsofuse:'termsofuse',
			zoom:'Zoom in',
			zoomMax:'Zoom max',
			drawTraceLine:'Draw trace lines',
			wasHere:'was here.',
			previousPoint:'<< Previous point',
			nextPoint:'Next point >>',
			noMorePastDataAvailable:'There is no more past point data available for this user',
			clearTraceLines:'Clear lines',
			operations:'Operations',
			photosTitle:'Photos',
			photosSearchBox:'Search photo according to uploader',
			usersSearchBox:'Search user',
			next:'Next >',
			previous:'< Previous',
			uploader:'Uploader',
			usernameLabel:'Username',
			passwordLabel:'Password',
			submitFormButtonLabel:'Submit',	
			cancelFormButtonLabel:'Cancel',
			incorrectPassOrUsername:'Incorrect username or password!',
			hi:'Hi',
			signout:'Sign out',
			rememberMeLabel:'Keep me logged in',
			emailLabel:'E-mail',
			emailNotFound:'E-mail address has not been found.',			
			sendNewPassword:'Send new password',
			showLoginForm:'Show login form',
			forgotPassword:'Forgot your password?',
			currentPasswordLabel:'Current password',
			newPasswordLabel:'New password',
			newPasswordAgainLabel:'New password(again)',
			enterSamePassword:'Please enter same password to password textboxes',
			newPasswordSent:'Your new password has been sent to your email',
			passwordChanged:'Password has been changed successfully',
			currentPasswordDoesntMatch:'Current password doesn\'t match',
			warningMissingParameter:'Missing parameter, if you fill a form please don\'t leave any required field blank',
			confirmationMessage:'Are you sure that you want to do that?',
			errorInOperation:'Error in operation',
			inviteUserLabel:'Invite'
		});
