
LAN_OPERATOR.addIndexes({
			mark:'Traceper Tracking System',	
			aboutTitle:'About',
			usersTitle:'Users',
			searchResultsTitle:'Search Results',
			returnToUserListLink:'&laquo; Return to user list',
			returnToPhotoListLink:'&laquo; Return to photo list',
//			loading:'Loading',
			noMatchFound:'no match found',
			realname:'Name',
			time:'Date',
			upLoadtime:'Upload time',
			deviceId:'Device id',
			latitude:'Latitude',
			longitude:'Longitude',
			searchStringIsTooShort:'Please write a longer word to search',			
			aboutus:'traceper is a GPS tracking system for mobile users, it is free, it is open source, it is simple. You can track and see your friends\' positions online.<br/><br/><div class=\"title\">Support</div>If you need support to modify and use this software, We can share all information we have, so feel free to contact us.<br/><br/><div class=\"title\">License</div>This software is free. It can be modified and distributed without notification.<br/><br/><div class=\"title\">Disclaimer</div>This software guarantees nothing, use it with your own risk. No responsilibity is taken for any situation.<br/><br/><div class=\"title\">Contact</div><a href=\"mailto:contact@mekya.com\">contact@mekya.com</a><br/><br/><div class=\"title\">Project Team</div><div id=\"projectteam\">Adnan Kalay - adnankalay@gmail.com <br/> Ahmet Oguz Mermerkaya - ahmetmermerkaya@gmail.com <br/> Eren Alp Celik - erenalpcelik@gmail.com <br/> Murat Salman - salman.murat@gmail.com </div>',
			termsofuse:'termsofuse',
			zoom:'Zoom in',
			zoomOut:'Zoom out',
			zoomMax:'Zoom max',
			drawTraceLine:'Draw trace lines',
			wasHere:'was here',
			previousPoint:'<< Previous point',
			nextPoint:'Next point >>',
			noPastDataAvailable:'There is no past point data available for this user',
			noMorePastDataAvailable:'There is no more past point data available for this user',
			clearTraceLines:'Clear lines',
			operations:'Operations',
			photosTitle:'Photos',
			photosSearchBox:'Search photo according to uploader',
			usersSearchBox:'Search user',
			next:'Next >',
			previous:'< Previous',
			uploader:'Uploader',
			usernameLabel:'Username',
			passwordLabel:'Password',
			submitFormButtonLabel:'Submit',
			login:'Login',
			cancelFormButtonLabel:'Cancel',
			incorrectPassOrUsername:'Incorrect username or password!',
			unauthorizedAccess:'Unauthorized access',
			hi:'Hi',
			signout:'Logout',
			rememberMeLabel:'Keep me logged in',
			emailLabel:'E-mail',
			invitationMessage:'Message:',
			emailNotFound:'E-mail address has not been found.',			
			sendNewPassword:'Send new password',
			forgotPassword:'Forgot your password?',
			currentPasswordLabel:'Current password',
			newPasswordLabel:'New password',
			newPasswordAgainLabel:'New password(again)',
			enterSamePassword:'Please enter same password to password textboxes',
			newPasswordSent:'Your new password has been sent to your email',
			passwordChanged:'Password has been changed successfully',
			currentPasswordDoesntMatch:'Current password doesn\'t match',
			warningMissingParameter:'Missing parameter, if you fill a form please don\'t leave any required field blank',
			confirmationMessage:'Are you sure that you want to do that?',
			addFriendRequestConfirmation:'Are you sure that you want to send friend request to %s?',
			acceptFriendRequestConfirmation:'Are you sure that you want to confirm friend request from %s?',
			deleteFriendshipConfirmation:'Are you sure that you want to delete %s from friend list?',
			errorInOperation:'Error in operation',
			inviteUserLabel:'Invite',
			dataRecordedCheckYourEmail:'Your data is recorded successfully, check your email to activate your account',
			emailAlreadyExist:'This email is already registered.If you want, you can use \'Forgot your password\'',
			emailNotValid:'Email you entered is not valid!',
			activateAccountSuccesful:'Your account activated successfully. You can LogIn now.',
			activatedAccountMailNotFound:'Your email address has not been found in activation list.',
			activatedAccountKeysDontMatch:'Something wrong, make sure your link is correct.',
			HomePage:'Home',
			changePassword:'Change Password',
			friendRequestRecorded:'Your friend request is recorded successfully',
			friendRequests:'Friend Requests',
			sendInvitations:'Send invitations to your friends',
			invitationSentSuccesfull:'All invitation has been sent successfully',
			invitationSentPartial:'Invitations has been sent, but wrong-formatted e-mail address found',
			mailEntranceRule:'Please separate e-mail addresses with semicolon(;)',
			registerLabel:'Register',
			unauthorizedCommentDeletion:'You are not allowed to delete this comment.',
			didYouMean:'Did you mean',
			ifSoClickOnSuggestedEmail:'If so, click on the suggested e-mail for correcting the entry. If not, please ignore this message.',
			registerEmailNotificationMessage:'After you send the sign up form by filling it correctly, an account activation e-mail message will be sent to the e-mail adress specified at this field. When you click the account activation link at this message, you will have completed the registration process successfully. Therefore please enter a valid e-mail address that you use into this field.',
			userSearchNotificationMessage:'It is enough to type your friend\'s name and click on the "Search" button in order to search your friends at Traceper. If your friend is a member of Traceper, he/she will be listed. If not listed, you could invite your friends to Traceper via the link <div class="lo-icon-in-tooltip icon-inviteUsers"></div>(Invite Friends) at the top menu.',
			uploadSearchNotificationMessage:'It is enough to type a keyword and click on the "Search" button in order to search the photos that you and your friends shared or the ones that are shared publicly. We shall list all the photos that meet your search criteria.',
			invitedEmailsNotificationMessage:'Please enter your friends\' e-mails into this field separated by the <b>space</b>, <b>comma</b> or <b>ENTER</b> characters in order to invite them to Traceper.',
			QRCodeNotificationMessage:'You could download our mobile application to your phone in which Android 2.2 or above installed, by scanning the QR code on the left with any QR code scanner.',			
			youHaveNoValidLocationInfo:'You have not sent any location info with mobile app yet. Therefore we could not display your location on the map. If you have not installed our mobile app yet, you could do so using the links <div class="lo-icon-in-tooltip icon-download1"></div> or <div class="lo-icon-in-tooltip icon-qrcode"></div> at the bottom-left part of the page. After logging in with mobile app, you could begin to share your location info.',
			yourFriendHasNoValidLocationInfo:'Your friend has not sent location info with mobile app yet. Therefore we could not display his/her location on the map. You will see his/her time-stamped location on the map, when he/she sends location info with mobile app at least for once.',
			yourLocationInfoNotReliable:'You have not sent any location info with mobile app yet. We have detected your location via IP geolocation. Accuracy of IP geolocation is highly low. We are displaying your location detected over IP as a rough estimate until you send reliable information by mobile app. If you have not installed our mobile app yet, you could do so using the links <div class="lo-icon-in-tooltip icon-download1"></div> or <div class="lo-icon-in-tooltip icon-qrcode"></div> at the bottom-left part of the page. After logging in with mobile app, you could begin to share your highly reliable location info.',
			yourFriendsLocationInfoNotReliable:'Your friend has not sent location info with mobile app yet. We have detected his/her location via IP geolocation. Accuracy of IP geolocation is highly low. We are displaying his/her location detected over IP as a rough estimate, until he/she sends reliable information by mobile app. After he/she sends location info by mobile app, you could view your friend\'s timestamped and highly reliable location info.',
			geolocationNotificationMessage:'You could henceforth share your location info via web thanks to HTML5 geolocation. In order for us to get your location info, you have to give permission. Therefore in order to update your location info, you should give the location sharing permission that your browser will ask for as soon as you log in. Some browsers can remember your permission for a period of time with respect to your choice. If your browser supports this feature, you will not have to give permission for each login process.'
	});
