
LAN_OPERATOR.addIndexes({
			mark:'Traceper Takip Sistemi',		
			aboutTitle:'Hakk\u0131m\u0131zda',
			usersTitle:'Kullan\u0131c\u0131lar',
			searchResultsTitle:'Arama Sonu\u00E7lar\u0131',
			returnToUserListLink:'&laquo; Kullan\u0131c\u0131 listesine d\u00F6n',
			returnToPhotoListLink:'&laquo; Resimler listesine d\u00F6n',
//			loading:'Y\u00FCkleniyor',
			noMatchFound:'Uygun sonu\u00E7 bulunamad\u0131',
			realname:'Ad',
			time:'Zaman',
			upLoadtime:'Yükleme zamanı',
			deviceId:'Cihaz no',
			latitude:'Enlem',
			longitude:'Boylam',
			searchStringIsTooShort:'L\u00FCtfen aranmas\u0131 i\u00E7in daha uzun kelime giriniz.',
		    aboutus:'<div class=\"logo\"></div>traceper akıllı telefonları kullanıcıları için bir GPS takip sistemidir, traceper ücretsiz, açık kaynak kodlu ve kullanımı basit bir yazılımdır. Traceper ile arkadaşlarınızın nerede olduklarını görebilirsiniz.<br/><br/><div class=\"title\">Destek</div>Bu yazılımı kullanmak veya değiştirmek isterseniz sahip olduğumuz tüm bilgiyi paylaşmaya hazırız, bu yüzden lütfen iletişime geçmek için tereddüt yaşamayınız.<br/><br/><div class=\"title\">Lisans</div>Bu yazılım ücretsizdir, haber vermeden değiştirilebilir veya dağıtılabilir.<br/><br/><div class=\"title\">Tekzip</div>Bu yazılım hiç bir şeyi garanti etmez, yazılımı kullanırken bütün sorumluluk kullanana aittir. Herhangi bir durumda kesinlikle sorumluluk kabul edilmez.<br/><br/><div class=\"title\">İletişim</div><a href=\"mailto:contact@mekya.com\">contact@mekya.com</a><br/><br/><div class=\"title\">Proje Ekibi</div><div id=\"projectteam\">Adnan Kalay - adnankalay@gmail.com <br/> Ahmet Oğuz Mermerkaya - ahmetmermerkaya@gmail.com <br/> Eren Alp Çelik - erenalpcelik@gmail.com <br/> Murat Salman - salman.murat@gmail.com </div>',
			zoom:'Yakınlaştır',
			zoomOut:'Uzaklaştır',
			zoomMax:'En yakın',
			drawTraceLine:'İz doğrularını çiz',
			wasHere:'buradaydı',
			previousPoint:'<< Önceki nokta',
			nextPoint:'Sonraki nokta >>',
			noPastDataAvailable:'Bu kullanıcı için geçmiş iz bilgisi mevcut değil',
			noMorePastDataAvailable:'Bu kullan\u0131c\u0131 i\u00E7in daha fazla geçmiş iz bilgisi mevcut değil',
			clearTraceLines:'Geçmiş izleri temizle',
			operations:'İşlemler',
			photosTitle:'Resimler',
			photosSearchBox:'Yükleyene göre resim ara',
			usersSearchBox:'Kullanıcı ara',
			next:'Sonraki >',
			previous:'< Önceki',
			uploader:'Yükleyen',
			usernameLabel:'Kullan\u0131c\u0131 Ad\u0131',
			passwordLabel:'Şifre',
			submitFormButtonLabel:'G\u00F6nder',
			login:'Giriş',
			cancelFormButtonLabel:'Vazge\u00E7',
			incorrectPassOrUsername:'Kullan\u0131c\u0131 Ad\u0131 veya şifre hatalı!',
			unauthorizedAccess:'Yetkisiz kullanım',
			hi:'Selam',
			signout:'Çıkış',
			rememberMeLabel:'Beni hatırla',
			emailLabel:'E-posta',
			invitationMessage:'Mesaj:',
			emailNotFound:'E-posta adresi bulunamadı.',
			sendNewPassword:'Yeni şifre gönder',
			forgotPassword:'Şifremi unuttum',
			currentPasswordLabel:'Şimdiki şifre',
			newPasswordLabel:'Yeni şifre',
			newPasswordAgainLabel:'Yeni şifre(tekrar)',
			enterSamePassword:'Lütfen yeni şifre kutucuklarına aynı şifreyi giriniz',
			newPasswordSent:'Yeni şifre e-posta adresinize gönderilmiştir.',
			passwordChanged:'Şifre başarıyla değiştirildi',
			currentPasswordDoesntMatch:'Girilen şifre şimdiki şifre ile aynı değil',
			warningMissingParameter:'Eksik parametre, form dolduruyorsanız lütfen tüm gerekli alanları boş bırakmayınız',
			confirmationMessage:'Bu işlemi yapmak istediğinize emin misiniz?',
			addFriendRequestConfirmation:'%s kullan\u0131c\u0131s\u0131na arkadaşl\u0131ık isteği göndermek isteğinize emin misiniz?',
			acceptFriendRequestConfirmation:'%s kullan\u0131c\u0131s\u0131n\u0131n arkadaşl\u0131ık isteğini onayl\u0131yor musunuz?',
			deleteFriendshipConfirmation:'%s kullan\u0131c\u0131s\u0131n\u0131 arkadaş listenizden ç\u0131karmak isteğinize emin misiniz?',
			errorInOperation:'İşlem yapılamadı!',
			inviteUserLabel:'Davetiye gönder',
			dataRecordedCheckYourEmail:'Bilgileriniz başarıyla kaydedilmiştir, hesabınızı aktif hale getirmek için e-mailinizi kontrol ediniz.',
			emailAlreadyExist:'Bu e-posta adresi kayıtlarda zaten bulunmaktadır. İsterseniz, \'Şifremi unuttum\'u kullanabilirsiniz. ',
			emailNotValid:'Girdiğiniz e-posta adresi e-posta yapısında değildir!!',
			activateAccountSuccesful:'Hesabınız onaylanmıştır. Giriş yapabilirsiniz.',
			activatedAccountMailNotFound:'E-posta adresiniz aktivasyon listemizde bulunamadı.',
			activatedAccountKeysDontMatch:'Bir seyler hatalı olmalı, Baglantınızın dogru oldugundan emin olun.',
			HomePage:'Anasayfa',
			changePassword:'Şifremi değiştir',
			friendRequestRecorded:'Arkadaşlık isteği başarıyla kaydedildi.',
			friendRequests:'Arkadaşlık istekleri',
			sendInvitations:'Arkadaşlarınıza davetiye gönderin',
			invitationSentSuccesfull:'Davetiyeler başarıyla gönderildi.',
			invitationSentPartial:'Davetiyeler gönderildi yalnız uygun formatta olmayan e-posta adresleri bulundu',
			mailEntranceRule:'Lütfen e-posta adreslerini noktalı virgül(;) ile ayırınız.',
			registerLabel:'Kayıt Ol',
			unauthorizedCommentDeletion:'Bu yorumu silmeye yetkiniz yoktur.',
			didYouMean:'mu demek istediniz',
			ifSoClickOnSuggestedEmail:'Öyleyse girişi düzeltmek için önerilen e-postaya tıklayınız. Girişinizin doğru olduğunu düşünüyorsanız lütfen bu mesajı önemsemeyin.',
			registerEmailNotificationMessage:'Kayıt formunu hatasızca doldurup gönderdiğinizde, bu alanda belirttiğiniz e-posta adresine hesap aktivasyon e-postası gönderilecektir. Bu e-postadaki bağlantıya tıklayarak hesabınızı etkinleştirdiğinizde kayıt işlemini başarıyla tamamlamış olacaksınız. Bu nedenle lütfen bu alana geçerli ve kullandığınız bir e-posta adresi giriniz.',
			userSearchNotificationMessage:'Arkadaşlarınızı Traceper\'da aramak için arkadaşınızın ismini bu alana yazıp "Ara" butonuna tıklamanız yeterli. Eğer arkadaşınız Traceper üyesiyse listede çıkacaktır. Eğer arkadaşınız listede çıkmazsa kendisini Traceper\'a davet etmek için üst menüdeki <div class="lo-icon-in-tooltip icon-inviteUsers"></div>(Arkadaşlarını Davet Et) bağlantısını kullanabilirsiniz.',
			uploadSearchNotificationMessage:'Sizin ve arkadaşlarınızın paylaştıkları veya herkese açık olarak paylaşılan fotoğrafları aramak için bu alana bir anahtar kelime yazmanız ve "Ara" butonuna basmanız yeterli. Aradığınız kritere uyan tüm fotoğrafları sizin için listeleyeceğiz.',
			invitedEmailsNotificationMessage:'Traceper\'a davet etmek istediğiniz arkadaşlarınızın e-posta adreslerini lütfen <b>boşluk</b>, <b>virgül</b> veya <b>ENTER</b> karakaterleri ile ayırarak bu alana giriniz.',
			QRCodeNotificationMessage:'Soldaki QR kodu Android 2.2 veya üstü işletim sistemi yüklü telefonunuzda bulunan herhangi bir QR kod tarayıcısıyla tarayarak mobil uygulamamızı cihazınıza indirebilirsiniz.',
			youHaveNoValidLocationInfo:'Mobil uygulama ile henüz hiç konum bilgisi göndermemişsiniz. Bu nedenle harita üzerinde konumunuzu görüntüleyemiyoruz. Mobil uygulamamızı henüz yüklemediyseniz, sayfanın sol altındaki <div class="lo-icon-in-tooltip icon-download1"></div> veya <div class="lo-icon-in-tooltip icon-qrcode"></div> bağlantılarını kullanarak yükleyebilir ve uygulamada oturum açarak konum bilginizi paylaşmaya başlayabilirsiniz.',
			yourFriendHasNoValidLocationInfo:'Arkadaşınız mobil uygulama ile henüz hiç konum bilgisi göndermemiş. Bu nedenle konumunu harita üzerinde görüntüleyemiyoruz. Mobil uygulama ile konum bilgisi gönderdiği andan itibaren arkadaşınızın konumunu zaman bilgisiyle birlikte harita üzerinde görebileceksiniz.',
			yourLocationInfoNotReliable:'Mobil uygulama ile henüz hiç konum bilgisi göndermemişsiniz. Konumunuzu web sitemize bağlandığınız IP üzerinden tespit ettik. IP üzerinden yer tespitinde hata payı çok yüksektir. Mobil uygulama üzerinden güvenilir konum bilgisi gönderinceye kadar kabaca bir fikir vermesi açısından IP üzerinden tespit edilen konumunuzu gösteriyoruz. Mobil uygulamamızı henüz yüklemediyseniz, sayfanın sol altındaki <div class="lo-icon-in-tooltip icon-download1"></div> veya <div class="lo-icon-in-tooltip icon-qrcode"></div> bağlantılarını kullanarak yükleyebilir ve uygulamada oturum açarak konum bilginizi yüksek doğrulukta paylaşmaya başlayabilirsiniz.',
			yourFriendsLocationInfoNotReliable:'Arkadaşınız mobil uygulama ile henüz hiç konum bilgisi göndermemiş. Konumunu web sitemize bağlandığı IP üzerinden tespit ettik. IP üzerinden yer tespitinde hata payı çok yüksektir. Arkadaşınız mobil uygulama üzerinden güvenilir konum bilgisi gönderinceye kadar kabaca bir fikir vermesi açısından IP üzerinden tespit edilen konumunu gösteriyoruz. Mobil uygulama ile konum bilgisi gönderdiği andan itibaren arkadaşınızın konumunu zaman bilgisiyle birlikte ve yüksek doğrulukta harita üzerinde görebileceksiniz.',
			geolocationNotificationMessage:'Artık HTML5 geolocation sayesinde web üzerinden de konum bilginizi paylaşabilirsiniz. Konum bilginizi alabilmemiz için izin vermeniz gerekmektedir. Bu nedenle konum bilginizin güncellenebilmesi için oturum açmanızla birlikte tarayıcınızın isteyeceği konum paylaşım iznine lütfen olumlu cevap veriniz. Bazı tarayıcılar sizin seçiminize göre izninizi belli bir süre hatırlayabilir. Tarayıcınız bunu destekliyorsa bu sayede her oturum açışınızda izin vermeniz gerekmeyecektir.',
			jan:'Oca',
			feb:'Şub',
			mar:'Mar',
			apr:'Nis',
			may:'May',
			jun:'Haz',
			jul:'Tem',
			aug:'Ağu',
			sep:'Eyl',
			oct:'Eki',
			nov:'Kas',
			dec:'Ara',
			year:'yıl',
			month:'ay',
			day:'gün',
			hour:'saat',
			minute:'dakika',
			second:'saniye',
			pluralSuffix:'',
			ago:'önce',
			thisPhotoIsUnavailable:'Bu fotoğrafa maalesef erişilemiyor...'
		});
