<?php 
/**
 * this file is the translation of views/lagouts/main.php
 */
return array(
	'Traceper Info' => 
	'<b>traceper</b> is a location-based social network service for mobile users. The use of this service is simple and completely free. You can track and see your friends\' and family members\' positions online by means of this service. Moreover, you could share the photos taken by the mobile application as location-labeled just with your friends or as public with respect to your choice. <br/><br/>
	<div class=\"title\"><b><font size="3">Support</font></b></div>
	If you need support to use this service, we can share all information we have. So feel free to contact us. <br/><br/>
	<div class=\"title\"><b><font size="3">License</font></b></div>
	This service is completely free. <br/><br/>
	<div class=\"title\"><b><font size="3">Disclaimer</font></b></div>
	This service guarantees nothing, use it with your own risk. No responsilibity is taken for any situation. Please read our Terms of Use for detailed information. <br/><br/>
	<div class=\"title\"><b><font size="3">Blog Address</font></b></div>
	<a href="http://traceper.blogspot.com"><font color="blue">http://traceper.blogspot.com</font></a> <br/><br/>
	<div class=\"title\"><b><font size="3">Contact</font></b></div>
	contact@traceper.com <br/><br/>',
	
	
	'Traceper Terms' =>
	'<b>Last Updated: October 28, 2013</b> </br></br>
	<b><font size="5">TRACEPER TERMS OF USE</font></b> </br></br>
	PLEASE READ THESE TERMS OF USE CAREFULLY BEFORE USING THE SERVICES OFFERED BY TRACEPER. THESE TERMS OF USE SET FORTH THE LEGALLY BINDING TERMS AND CONDITIONS FOR YOUR USE OF THE WEBSITE AT <a href="http://www.traceper.com"><font color="blue">HTTP://TRACEPER.COM</font></a> AND ALL OF THE SERVICES AND APPLICATIONS OFFERED BY TRACEPER. </br></br>
	<b><font size="3">Acceptance of Terms</font></b> </br></br>
	By registering for or using the Service in any manner you agree to all of the terms of use contained herein. </br></br>
	<b><font size="3">Access</font></b> </br></br>
	Subject to these Terms of Use, Traceper may offer to provide the service solely for your own use, and not for the use or benefit of any third party. </br></br>
	<b><font size="3">Registration and Eligibility</font></b> </br></br>
	Eventhough you may browse the Site without registering, you are required to sign up for Traceper in order to be able to use the Service completely. You are required to covenant that you provide Traceper with accurate and complete registration information and keep your registration information accurate and up-to-date. Failure to do so shall constitute a breach of these Terms of Use, which may result in termination of your Traceper account. </br></br>
	You shall not do the following actions while using this Service: </br></br>
	<ul class="termsLists">
	<li>Create any account for anyone without such person\'s permission,</li>
	<li>Create more than one personal account,</li>
	<li>Create another account without our permission, if we disable your account,</li>
	<li>Share your password, let anyone else access your account, or do anything else that might jeopardize the security of your account,</li>
	<li>Transfer your account to anyone without first getting our written permission,</li>
	<li>Use the first and last names of another person with the intent to impersonate that person,</li>
	<li>Use a Traceper account that is subject to any rights of a person other than you without appropriate authorization, or</li>
	<li>Use a first name, last name or e-mail address  that is otherwise offensive, vulgar or obscene or otherwise unlawful.</li>
	</ul> </br>
	Traceper reserves the right to refuse registration of, or cancel an account in its sole discretion. You are solely responsible for the activities that occur on your account. You shall be responsible for maintaining the confidentiality of your Traceper password. </br></br>
	You represent and warrant that if you are an individual, you are of legal age to form a binding contract, or that if you are registering on behalf of an entity, that you are authorized to enter into, and bind the entity to, these Terms of Use and register for the Service. The Service is not available to individuals who are younger than 13 years old. Traceper may, in its sole discretion, refuse to offer the Service to any person or entity and change its eligibility criteria at any time. You are solely responsible for ensuring that these Terms of Use are in compliance with all laws, rules and regulations applicable to you and the right to access the Service is revoked where these Terms of Use or use of the Service is prohibited and, in such circumstances, you agree not to use or access the Site or Services in any way. </br></br>
	<b><font size="3">Content</font></b> </br></br>
	All Content, whether publicly posted or privately transmitted, is the sole responsibility of the person who originated such Content. Traceper cannot guarantee the authenticity of any Content or data which users may provide about themselves. You acknowledge that all Content accessed by you using the Service is at your own risk and Traceper will not be responsible and will not be liable for any damage or loss to you or any other party resulting therefrom. The term "Content" in this Terms of Use includes, without limitation, location information, videos, audio clips, comments, information, data, text, photographs, software, scripts, graphics, and interactive features generated, provided, or otherwise made accessible by Traceper on or through the Service. Content added, created, uploaded, submitted, distributed, posted or otherwise obtained through the Service by users, including Content that is added to the Service in connection with users linking their accounts to third party websites and services, is referred to as, "User Content". </br></br>
	<b><font size="3">Traceper Content</font></b> </br></br>
	The Service contains Content specifically provided by Traceper or its partners and such Content is protected by copyrights, trademarks, service marks, patents, trade secrets or other proprietary rights and laws, as applicable. You shall abide by and maintain all copyright notices, information, and restrictions contained in any Content accessed through the Service. </br></br>
	Subject to these Terms of Use, Traceper grants each user of the Site and/or Service a worldwide, non-exclusive, non-sublicensable and non-transferable license to use, modify and reproduce the Content, solely for personal, non-commercial use. Use, reproduction, modification, distribution or storage of any Content for other than personal, non-commercial use is expressly prohibited without prior written permission from Traceper, or from the copyright holder identified in such Content\'s copyright notice, as applicable. You shall not sell, license, rent, or otherwise use or exploit any Content for commercial (whether or not for profit) use or in any way that violates any third party right. </br></br>
	<b><font size="3">User Content</font></b> </br></br>
	We may use your User Content in a number of different ways in connection with the Site, Service and Traceper\’s business as Traceper may determine in its sole discretion, including but not limited to, publicly displaying it, reformatting it, incorporating it into marketing materials, advertisements and other works, creating derivative works from it, promoting it, distributing it, and allowing other users to do the same in connection with their own websites, media platforms, and applications (“Third Party Media”). By submitting User Content on the Site or otherwise through the Service, you hereby do and shall grant Traceper a worldwide, non-exclusive, royalty-free, fully paid, sublicensable and transferable license to use, copy, edit, modify, reproduce, distribute, prepare derivative works of, display, perform, and otherwise fully exploit the User Content in connection with the Site, the Service and Traceper\’s (and its successors and assigns\') business, including without limitation for promoting and redistributing part or all of the Site (and derivative works thereof) or the Service in any media formats and through any media channels (including, without limitation, third party websites and feeds). You also hereby do and shall grant each user of the Site and/or the Service, including Third Party Media, a non-exclusive license to access your User Content through the Site and the Service, and to use, edit, modify, reproduce, distribute, prepare derivative works of, display and perform such User Content in connection with their use of the Site, Service and Third Party Media. </br></br>
	You represent and warrant that you have all rights to grant such license to us without infringement or violation of any third party rights, including without limitation, any privacy rights, publicity rights, copyrights, contract rights, or any other intellectual property or proprietary rights. </br></br>
	You understand that all information publicly posted or privately transmitted through the Site is the sole responsibility of the person from which such Content originated; that Traceper will not be liable for any errors or omissions in any Content; and that Traceper cannot guarantee the identity of any other users with whom you may interact in the course of using the Service. </br></br>
	When you delete your User Content, they will be removed from the Service. However, you understand that any removed User Content may persist in backup copies for a reasonable period of time (but following removal will not be shared with others) or may remain with users who have previously accessed or downloaded your User Content. </br></br>
	When you publish content or information using the Public setting, it means that you are allowing everyone, including people off of Traceper, to access and use that information, and to associate it with you. </br></br>
	We always appreciate your feedback or other suggestions about Traceper, but you understand that we may use them without any obligation to compensate you for them (just as you have no obligation to offer them). </br></br>
	<b><font size="3">Rules and Conduct</font></b> </br></br>
	You promise not to use the Service for any purpose that is prohibited by these Terms of Use. You are responsible for all of your activity in connection with the Service. Additionally, you shall abide by all applicable local, state, national and international laws and regulations and, if you represent a business, any advertising, marketing, privacy, or other self-regulatory code(s) applicable to your industry. </br></br>
	You shall not (and shall not permit any third party to) either (a)take any action or (b)upload, download, post, submit or otherwise distribute or facilitate distribution of any Content on or through the Service that but not limited with: </br></br>
	<ul class="termsLists">
	<li>infringes any patent, trademark, trade secret, copyright, right of publicity or other right of any other person or entity or violates any law or contractual duty;</li>
	<li>you know is false, misleading, untruthful or inaccurate;</li>
	<li>is unlawful, threatening, abusive, harassing, defamatory, libelous, deceptive, fraudulent, invasive of another\'s privacy, tortious, obscene, vulgar, pornographic, offensive, profane, contains or depicts nudity, contains or depicts sexual activity, promotes bigotry, discrimination or violence, or is otherwise inappropriate as determined by Traceper in its sole discretion; </li>
	<li>constitutes unauthorized or unsolicited advertising, junk or bulk e-mail ("spamming");</li>
	<li>involves commercial activities (whether or not for profit) and/or sales without Traceper’s prior written consent such as contests, sweepstakes, barter, advertising, or pyramid schemes;</li>
	<li>contains software viruses or any other computer codes, files, worms, logic bombs or programs that are designed or intended to disrupt, disable, damage, limit or interfere with the proper function of any software, hardware, or telecommunications equipment or to damage or obtain unauthorized access to any system, data, password or other information of Traceper or any third party;</li>
	<li>impersonates any person or entity, including any employee or representative of Traceper;</li>
	<li>includes anyone\'s identification documents or sensitive financial information; or</li>
	<li>breaches any of the other policies and rules incorporated herein.</li>
	</ul> </br>
	If the User Content includes a photograph or a video: </br></br>
	<ul class="termsLists">
	<li>Though nudity is natural, not everyone wants to see it. The same goes for hateful things, spam, and irrelevant photos or videos. So you shall steer away from naked people, mean-ness, gross-ness, inappropriate-ness and anything else that you wouldn\'t want to see when you\'re exploring;</li>
	<li>You shall not take photos or videos that include people\'s private information, like a credit card number or phone number. </li>
	<li>You shall not upload a photo or video of anyone who doesn\'t want their picture or video uploaded.</li>
	</ul> </br>
	Traceper has a zero-tolerance policy against child pornography, and will terminate and report to the appropriate authorities when any user is detected to publish or distribute child pornography. </br></br>
	Traceper does not guarantee that any Content or User Content will be made available on the Site or through the Service. Traceper has no obligation to monitor the Site, Service, Content, or User Content. However, Traceper reserves the right to (i) remove, suspend, edit or modify any Content in its sole discretion, including without limitation any User Content at any time, without notice to you and for any reason (including, but not limited to, upon receipt of claims or allegations from third parties or authorities relating to such Content or if Traceper is concerned that you may have violated these Terms of Use), or for no reason at all and (ii) to remove, suspend or block any User Content from the Service. Traceper also reserves the right to access, read, preserve, and disclose any information as Traceper reasonably believes is necessary to (i) satisfy any applicable law, regulation, legal process or governmental request, (ii) enforce these Terms of Use, including investigation of potential violations hereof, (iii) detect, prevent, or otherwise address fraud, security or technical issues, (iv) respond to user support requests, or (v) protect the rights, property or safety of Traceper, its users and the public. </br></br>
	<b><font size="3">Third Party Sites and Services</font></b> </br></br>
	The Service may permit you to link to other websites, services or resources on the Internet, and other websites, services or resources may contain links to the Site. You Access third party websites at your own risk. Third party websites are not under Traceper’s control. You acknowledge that Traceper is not responsible for any inappropriateness of such websites. You agree that Traceper shall not be responsible for any damage or loss caused by any use of third party websites. </br></br>
	<b><font size="3">Warranty Disclaimer</font></b> </br></br>
	You release Traceper from all liability for you having acquired or not acquired Content through the Service. The Service may contain, or direct you to websites containing, information that some people may find offensive or inappropriate. Traceper will not be responsible or liable for the accuracy, copyright compliance, legality or decency of material contained in or accessed through the Service. </br></br>
	You release us from all liability relating to your relationships with other users. You understand that we do not, in any way, screen users, nor do we inquire into the backgrounds of users or attempt to verify their backgrounds or statements. We make no representations or warranties as to the conduct of users or the veracity of any information users provide. In no event shall we be liable for any damages whatsoever, whether direct, indirect, general, special, compensatory, consequential, and/or incidental, arising out of or relating to the conduct of you or anyone else in connection with the Services, including, without limitation, bodily injury, emotional distress, and any damages resulting in any way from communications or meetings with users or persons you may otherwise meet through the Services. As such, you agree to take reasonable precautions and exercise the utmost personal care in all interactions with any individual you come into contact with through the Services, particularly if you decide to meet such individuals in person. </br></br>
	THE SITE, SERVICE AND CONTENT ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT ANY REPRESENTATIONS OR WARRANTIES OF ANY KIND. </br></br>
	TRACEPER, AND ITS DIRECTORS DO NOT WARRANT THAT: (A) THE SERVICE WILL BE SECURE OR AVAILABLE AT ANY PARTICULAR TIME OR LOCATION; (B) ANY DEFECTS OR ERRORS WILL BE CORRECTED; (C) ANY CONTENT OR SOFTWARE AVAILABLE AT OR THROUGH THE SERVICE IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS; OR (D) THE RESULTS OF USING THE SERVICE WILL MEET YOUR REQUIREMENTS. YOUR USE OF THE WEBSITE, SERVICE AND CONTENT IS SOLELY AT YOUR OWN RISK. </br></br>
	<b><font size="3">Limitation of Liability</font></b> </br></br>
	ALL LIABILITY OF TRACEPER AND ITS DIRECTORS HOWSOEVER ARISING FOR ANY LOSS SUFFERED AS A RESULT OF YOUR USE THE SITE, SERVICE OR CONTENT IS EXPRESSLY EXCLUDED TO THE FULLEST EXTENT PERMITTED BY LAW, SAVE THAT, IF A COURT OF COMPETENT JURISDICTION DETERMINES THAT LIABILITY OF TRACEPER AND ITS DIRECTORS HAS ARISEN. </br></br>
	TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, TRACEPER AND ITS DIRECTORS SHALL NOT BE LIABLE IN ANY EVENT WITH RESPECT TO THE SITE, SERVICE OR CONTENT. </br></br>
	<b><font size="3">Integration and Severability</font></b> </br></br>
	These Terms of Use are the entire agreement between you and Traceper with respect to the Service and use of the Site, Service, Content or User Content, and supersede all prior proposals (whether oral, written or electronic) between you and Traceper with respect to the Site. If any provision of these Terms of Use is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that these Terms of Use will otherwise remain in full force and effect and enforceable. The failure of either party to exercise in any respect any right provided for herein shall not be deemed a waiver of any further rights hereunder. Waiver of compliance in any particular instance does not mean that we will waive compliance in the future. In order for any waiver of compliance with these Terms of Use to be binding, Traceper must provide you with written notice of such waiver through one of its authorized representatives. </br></br>
	<b><font size="3">Modification of Terms of Use</font></b> </br></br>
	Traceper reserves the right, at its sole discretion, to remove and modify any of these Terms of Use, or add new terms at any time by posting a notice on the Site or by sending you notice through the Service or via email. Traceper may also impose limits on certain features and services or restrict your access to parts or all of the Service without notice or liability. It is your responsibility to check these Terms of Use periodically for changes. Your continued use of the Service following the posting of any changes to these Terms of Use constitutes acceptance of those changes. </br></br>
	<b><font size="3">Termination</font></b> </br></br>
	Traceper may terminate your access to all or any part of the Service at any time, with or without cause, with or without notice, effective immediately, which may result in the forfeiture and destruction of all information associated with your membership. If you wish to terminate your account, you may do so by sending an e-mail with a subject of “Account Termination” to our contact address (contact@traceper.com). All provisions of these Terms of Use which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability </br></br>
	<b><font size="3">Indemnification</font></b> </br></br>
	You shall defend, indemnify, and hold harmless Traceper and its directors from all losses, costs or liabilities, that arise from your use of the Site, Service or Content or the violation of these Terms of Use, or infringement by you, or any third party using your account, of any intellectual property or other right of any person or entity (save to the extent that a court of competent jurisdiction holds that such claim arose due to an act or omission of Traceper). Traceper reserves the right to assume the exclusive defense and control of any matter otherwise subject to indemnification by you. </br></br>
	<b><font size="3">Other</font></b> </br></br>
	Traceper shall not be liable for any failure to perform its obligations hereunder where such failure results from any cause beyond Traceper’s reasonable control, including, without limitation, mechanical, electronic or communications failure. These Terms of Use are personal to you, and are not assignable, transferable or sublicensable by you except with Traceper’s prior written consent. Traceper may assign, transfer or delegate any of its rights and obligations hereunder without consent. No agency, partnership, joint venture, or employment relationship is created as a result of these Terms of Use and neither party has any authority of any kind to bind the other in any respect. </br></br>
	<b>Effective Date: October 28, 2013</b>'		
);





?>