
LAN_OPERATOR.addIndexes({
			mark:'Public Reporter',	
			aboutTitle:'About',
			usersTitle:'Users',
			searchResultsTitle:'Search Results',
			returnToUserListLink:'&laquo; Return to user list',
			returnToPhotoListLink:'&laquo; Return to photo list',
//			loading:'Loading',
			noMatchFound:'no match found',
			realname:'Name',
			time:'Date',
			upLoadtime:'Upload time',
			deviceId:'Device id',
			latitude:'Latitude',
			longitude:'Longitude',
			searchStringIsTooShort:'Please write a longer word to search',			
			aboutus:'<div class=\"logo\"></div><a href=\"http://www.traceper.com\"><div id=\"traceper_logo\"></div></a></div>',
			termsofuse:'termsofuse',
			zoom:'Zoom in',
			zoomMax:'Zoom max',
			drawTraceLine:'Draw trace lines',
			wasHere:'was here.',
			previousPoint:'<< Previous point',
			nextPoint:'Next point >>',
			noMorePastDataAvailable:'There is no more past point data available for this user',
			clearTraceLines:'Clear lines',
			operations:'Operations',
			photosTitle:'Photos',
			photosSearchBox:'Search photo according to uploader',
			usersSearchBox:'Search user',
			next:'Next >',
			previous:'< Previous',
			uploader:'Uploader',
			usernameLabel:'Username',
			passwordLabel:'Password',
			submitFormButtonLabel:'Submit',	
			cancelFormButtonLabel:'Cancel',
			incorrectPassOrUsername:'Incorrect username or password!',
			hi:'Hi',
			signout:'Sign out',
			rememberMeLabel:'Keep me logged in',
			emailLabel:'E-mail',
			emailNotFound:'E-mail address has not been found.',			
			sendNewPassword:'Send new password',
			showLoginForm:'Show login form',
			forgotPassword:'Forgot your password?',
			currentPasswordLabel:'Current password',
			newPasswordLabel:'New password',
			newPasswordAgainLabel:'New password(again)',
			enterSamePassword:'Please enter same password to password textboxes',
			newPasswordSent:'Your new password has been sent to your email',
			passwordChanged:'Password has been changed successfully',
			currentPasswordDoesntMatch:'Current password doesn\'t match',
			warningMissingParameter:'Missing parameter, if you fill a form please don\'t leave any required field blank',
			confirmationMessage:'Are you sure that you want to do that?',
			errorInOperation:'Error in operation',
			inviteUserLabel:'Invite',
			dataRecordedCheckYourEmail:'Your data is recorded successfully, check your email to activate your account',
			emailAlreadyExist:'This email is already registered.If you want, you can use \'Forgot your password\'',
			emailNotValid:'Email you entered is not valid!',
			activateAccountSuccesful:'Your account activated successfully. You can Log In now.',
			activatedAccountMailNotFound:'Your email address has not been found in activation list.',
			activatedAccountKeysDontMatch:'Something wrong, make sure your link is correct.',
			HomePage:'Home',
			changePassword:'Change password',

	});
